# Generated by Django 3.0.5 on 2020-04-13 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chronos', '0011_absence_for_groups_and_rooms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='absence_reason',
        ),
    ]
