# Generated by Django 3.0.5 on 2020-04-27 13:52

from django.db import migrations, models
from django.db.models import F


class Migration(migrations.Migration):

    dependencies = [
        ('chronos', '0014_extra_lesson'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='abbrev',
            new_name='short_name',
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['name', 'short_name']},
        ),
    ]
