# Generated by Django 2.2.3 on 2019-07-24 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chronos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='abbrev',
            field=models.CharField(max_length=10, unique=True, verbose_name='Abbreviation of subject in timetable'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=30, unique=True, verbose_name='Long name of subject'),
        ),
        migrations.AlterUniqueTogether(
            name='timeperiod',
            unique_together={('weekday', 'period')},
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=30, unique=True, verbose_name='Long name'),
        ),
        migrations.AlterField(
            model_name='room',
            name='short_name',
            field=models.CharField(max_length=10, unique=True, verbose_name='Short name, e.g. room number'),
        ),
    ]
