# Generated by Django 2.2.3 on 2019-07-16 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cambro', '0001_initial'),
        ('chronos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='cambro.Room'),
        ),
    ]
