# Generated by Django 2.2.5 on 2019-09-07 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chronos', '0002_db_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonsubstitution',
            name='cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='lessonsubstitution',
            constraint=models.CheckConstraint(check=models.Q(('cancelled', True), ('subject__isnull', False), _negated=True), name='either_substituted_or_cancelled'),
        ),
    ]
