# Generated by Django 2.2.5 on 2019-09-07 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chronos', '0002_db_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonsubstitution',
            name='canceled',
            field=models.BooleanField(default=False),
        ),
    ]
