# Generated by Django 2.2.5 on 2019-09-14 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chronos', '0003_substitution_cancelled_or_subject'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='room',
            unique_together={('school', 'short_name')},
        ),
    ]
