# Generated by Django 2.2.4 on 2019-08-21 15:50

import biscuit.apps.chronos.util
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chronos', '0003_lesson_substitution'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessonperiod',
            name='substitution',
        ),
        migrations.AddField(
            model_name='lessonsubstitution',
            name='lesson_period',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='substitutions', to='chronos.LessonPeriod'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lessonsubstitution',
            name='week',
            field=models.IntegerField(
                default=biscuit.apps.chronos.util.current_week, verbose_name='Kalenderwoche'),
        ),
    ]
