# Generated by Django 2.2.4 on 2019-09-03 14:10

import biscuit.apps.chronos.util
import biscuit.core.util.core_helpers
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chronos', '0004_auto_20190821_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='school',
            field=models.ForeignKey(default=biscuit.core.util.core_helpers.get_current_school, on_delete=django.db.models.deletion.CASCADE, to='core.School'),
        ),
        migrations.AddField(
            model_name='lessonperiod',
            name='school',
            field=models.ForeignKey(default=biscuit.core.util.core_helpers.get_current_school, on_delete=django.db.models.deletion.CASCADE, to='core.School'),
        ),
        migrations.AddField(
            model_name='lessonsubstitution',
            name='school',
            field=models.ForeignKey(default=biscuit.core.util.core_helpers.get_current_school, on_delete=django.db.models.deletion.CASCADE, to='core.School'),
        ),
        migrations.AddField(
            model_name='room',
            name='school',
            field=models.ForeignKey(default=biscuit.core.util.core_helpers.get_current_school, on_delete=django.db.models.deletion.CASCADE, to='core.School'),
        ),
        migrations.AddField(
            model_name='subject',
            name='school',
            field=models.ForeignKey(default=biscuit.core.util.core_helpers.get_current_school, on_delete=django.db.models.deletion.CASCADE, to='core.School'),
        ),
        migrations.AddField(
            model_name='timeperiod',
            name='school',
            field=models.ForeignKey(default=biscuit.core.util.core_helpers.get_current_school, on_delete=django.db.models.deletion.CASCADE, to='core.School'),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Long name'),
        ),
        migrations.AlterField(
            model_name='room',
            name='short_name',
            field=models.CharField(max_length=10, verbose_name='Short name, e.g. room number'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='abbrev',
            field=models.CharField(max_length=10, verbose_name='Abbreviation of subject in timetable'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Long name of subject'),
        ),
        migrations.AlterUniqueTogether(
            name='room',
            unique_together={('school', 'name'), ('school', 'short_name')},
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('school', 'abbrev'), ('school', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='timeperiod',
            unique_together={('school', 'weekday', 'period')},
        ),
    ]
